### ISSUE TITLE
CSS3111: @font-face encountered unknown error

### ISSUE THREAD

**Issue by TechFounder** [bodrovis/jquery-slick-rails#14]
Hi, I'm getting an
```CSS3111: @font-face encountered unknown error```
```slick.eot?#iefix ```
on the IE9 console which completely blocks the site from rendering. When I remove the slick-theme that error goes away but of course I don't have the default theme. Any idea how to fix the problem?

**Comment by TechFounder** [comment]
I see that the theme file looks for fonts in /assets/fonts but there are no fonts there...

**Comment by TechFounder** [comment]
Is your recent UTF-8 fonts save causing a problem with ```slick.eot?#iefix format("embedded-opentype")```?

**Comment by bodrovis** [comment]
@TechFounder Hrm, that's strange. https://github.com/bodrovis/jquery-slick-rails/pull/13 here we actually converted the font, but after that cheched that everything is working correctly. Unfortunately, I do not have an IE9 available ATM. Could you please replace font file that you grabbed here with the one located here https://github.com/kenwheeler/slick/tree/master/slick/fonts and see if it helps?

**Comment by TechFounder** [comment]
Should I fork it, test it and if it works submitted as a PR?

**Comment by bodrovis** [comment]
Unfortunately, I don't really understand what's causing these problems with font file. It would be nice if you sent a PR, but I'll have to investigate more (probably by booting VM with IE9) and see if we can find a solution that suits all users.

**Comment by bodrovis** [comment]
Btw, here is the possible cause: https://stackoverflow.com/questions/11559592/ie9-css3111-font-face-encountered-unknown-error Not sure which converter Ken used when creating these fonts, but I'll give a shoot at FontSquirrel.

**Comment by bodrovis** [comment]
@TechFounder Could you use this branch https://github.com/bodrovis/jquery-slick-rails/tree/issue_with_eot_font_file and check if the issue remains?

**Comment by TechFounder** [comment]
Hi, I'm testing this on my coined branch right now and will let you know if this fixes it. Thanks.

**Comment by TechFounder** [comment]
In your new branch, did you replace the hot file with the version that's currently in the slick repo?

**Comment by bodrovis** [comment]
Yeah, I did. Originally, it was taken from there. I tried converting ttf to eot via FontSquirrel, but even on my IE11 it fails to load...

**Comment by TechFounder** [comment]
Are you saying that you're seeing the error on console as well?

**Comment by bodrovis** [comment]
Okay, simply speaking I tried two solutions:

1. Using the initial .eot file from the Slick's repo. This does work for me and I do not see any errors in IE11
2. Converting the initial .ttf file from the Slick's repo to .eot using FontSquirrel. It does not work for me, so in the new branch I stick to the initial font file.

Therefore, if this initial font file does not work for you, seems like the problem should be reported to Ken. If it does work, we'll probably have to stick to it.

**Comment by bodrovis** [comment]
Closed as per https://github.com/bodrovis/jquery-slick-rails/pull/15

**Comment by TechFounder** [comment]
Ok, I submitted the PR as instructed. Thanks.
