### ISSUE TITLE
Modifying slick-style.css

### ISSUE THREAD

**Issue by enjmusic** [bodrovis/jquery-slick-rails#17]
I've made a modified version of slick-style.css and put it in my assets/stylesheets directory. However, in slick-style.css, there are references to the slick fonts. How would I go about revising these references to use wherever this gem's fonts are so that my slider arrows can look like the slick arrows, and not the default arrow characters?

**Comment by bodrovis** [comment]
For Sass that'll be

```scss
asset-url('slick.eot');
// and other fonts...
```

Or: https://github.com/bodrovis/jquery-slick-rails/blob/master/app/assets/stylesheets/slick-theme.css.erb#L15

Hopefully I understood your question correctly.
