### ISSUE TITLE
Possible issue with height?

### ISSUE THREAD

**Issue by Pacn91** [bodrovis/jquery-slick-rails#26]
Hi, I don't know if this is an issue or it's intended to be like this. I'm using slick in my rails app, but I encounter a problem with the height of the images. I want my images to have the same height, for that I used adaptiveHeight: false, but this is still happening: ![gpdi9](https://user-images.githubusercontent.com/17788348/42321955-7a5ddda6-8052-11e8-9341-a94779ad1e73.jpg)

Why is that happening? And if is not a issue can you please tell me how to fix this without me fixing the height statically. 

Thank you!

**Comment by bodrovis** [comment]
Please review https://github.com/bodrovis/jquery-slick-rails/blob/master/CONTRIBUTING.md before opening issues :) Specifically:

> Please remember that this gem is merely a wrapper for the Slick jQuery plugin. This means that all issues related to Slick itself should not be reported here (there is a separate issue tracker for that). I am not an author of the Slick plugin and do not maintain it.
