### ISSUE TITLE
Does it support rails 6 so far?

### ISSUE THREAD

**Issue by martinnett** [bodrovis/jquery-slick-rails#30]
Hi, First of all, thanks for the good gem you provide. It's pretty good!

SO, **the question is does it work for rails 6?** 
If yes, is there any guide or installation recipe for rails 6, If No, do have any upgrade plan on that?

Thanks!!

**Comment by bodrovis** [comment]
Hi! Well, the simple answer is: yes, nothing prevents you from using it with Rails 6 but in Rails 5 style. However, I haven't really checked how it plays with Webpacker. Will try to research this today.

**Comment by martinnett** [comment]
Thank you for your quick reply. 

I found rails 6 put most plugins for frontend into pure javascript library even as turbolinks. Maybe I'm wrong, but I'm now trying out a similar plugin call `owl.carousel` and it works well on rails 6 basically.

**Comment by bodrovis** [comment]
I've briefly checked and here's a more detailed answer:

This gem works fine with Rails 6 without Webpacker. Use it as before, no changes.

If you have a Rails app with Webpacker then basically there's no need to use this gem. You just install JS/TS packages directly from npm:

```
yarn add jquery
yarn add slick-carousel
```

Then use them inside the `javascript/packs/application.js`:

```
var $ = require( "jquery" )
require("slick-carousel")

document.addEventListener("turbolinks:load", function() {
  $('.scroller').slick()
})
```

This repo contains sample apps showing both approaches in action: https://github.com/bodrovis/jquery-slick-rails-demo
