### ISSUE TITLE
Sass says file cannot be found slick.

### ISSUE THREAD

**Issue by BornALegend** [bodrovis/jquery-slick-rails#5]
Sass is saying that @Import 'slick'; cannot be found, but *= require slick works. Also, can you help me implement this plugin to my view. Ruby on Rails struggles with JavaScript at certain points. I followed the instructions to no avail. Please provide a short tutorial to assist me in getting this working on rails.

**Comment by bodrovis** [comment]
@BornALegend Sorry for the late response, I was having problems with Internet access. Will look into it today.

**Comment by bodrovis** [comment]
@BornALegend Well, I was not able to reproduce this error with Rails 4.2. Here is the demo app that you may use as a reference: https://github.com/bodrovis/jquery-slick-rails-demo

What is your version of Rails?

**Comment by BornALegend** [comment]
The server needed to be reset. Sorry.
