### ISSUE TITLE
Slick's stylesheets is not included

### ISSUE THREAD

**Issue by weldan** [bodrovis/jquery-slick-rails#9]
Even after @import 'slick' .

Please verify.

**Comment by bodrovis** [comment]
Please provide Ruby/Rails version you are using. Is it happening on production or development?

**Comment by bodrovis** [comment]
You may want to try the latest version that does not rely on Sass to be present. Check the updated Readme for instructions.

**Comment by bodrovis** [comment]
Closed due to inactivity. Feel free to re-open if the problem persists.
